#!/bin/bash

  chmod u+x -R $(dirname $(realpath $0))/Utilities/

  if [[ $# -eq 0 ]]; then
    fastfetch -c $HOME/.config/fastfetch/myconfig.jsonc
  fi

  ############## Menu ##############

    #   select MenuChoice in "Check for failed systemd services" "Check for errors in the log files" "Upgrade official packages" "Upgrade AUR packages" "Check for orphaned packages" "Clean packages cache" "Check disks health" "Reboot computer" "Exit program"

    # "Explicit Download Canvas"

    select MenuChoice in "Toggle Monitor Scaling" "Toggle Wacom Tablet" "Reboot Polybar" "Upgrade ALL using AUR" "Sudo Original Maintenance"  "Exit program"; do
    case $MenuChoice in

    "Toggle Monitor Scaling") 
        exec $(dirname $(realpath $0))/Utilities/8-Monitor-Toggle
        ;;

    "Toggle Wacom Tablet" ) exec $(dirname $(realpath $0))/Utilities/9-Wacom;;

    "Reboot Polybar" ) exec $(dirname $(realpath $0))/Utilities/10-Polybar;;

    "Upgrade ALL using AUR" ) exec $(dirname $(realpath $0))/Utilities/4-AURupgrade;;

    "Sudo-Original Maintenance" ) exec sudo $(dirname $(realpath $0))/ArchLinux-Maintenance-orig;;

    "Explicit Download Canvas" ) exec $(dirname $(realpath $0))/downloader/main.sh;;


    ############## Exit ##############

    "Exit program" ) exit;;

  ############## Menu end ##############

    esac

  done
