#!/bin/bash

  chmod u+x -R $(dirname $(realpath $0))/Utilities/

  if [[ $# -eq 0 ]]; then
    fastfetch -c $HOME/.config/fastfetch/myconfig.jsonc
  fi

  ############## Menu ##############

    #   select MenuChoice in "Check for failed systemd services" "Check for errors in the log files" "Upgrade official packages" "Upgrade AUR packages" "Check for orphaned packages" "Clean packages cache" "Check disks health" "Reboot computer" "Exit program"

    select MenuChoice in "Toggle Monitor Scaling" "Toggle Wacom Tablet" "Upgrade ALL using AUR" "Sudo Original Maintenance" "Explicit Download Canvas" "Exit program"; do
    case $MenuChoice in

    "Toggle Monitor Scaling") exec $(dirname $(realpath $0))/Utilities/8-Monitor-Toggle;;

    "Toggle Wacom Tablet" ) exec $(dirname $(realpath $0))/Utilities/9-Wacom;;

    "Upgrade ALL using AUR" ) exec $(dirname $(realpath $0))/Utilities/4-AURupgrade;;

    "Check for orphaned packages" ) exec $(dirname $(realpath $0))/Utilities/5-OrphanedCheck;;

    "Sudo-Original Maintenance" ) exec sudo $(dirname $(realpath $0))/ArchLinux-Maintenance-orig;;

    "Explicit Download Canvas" ) exec $(dirname $(realpath $0))/downloader/main.sh;;


    ############## Exit ##############

    "Exit program" ) exit;;

  ############## Menu end ##############

    esac

  done
