#!/bin/bash

    /home/frank/Documents/sjtu_canvas_downloader/main.sh &>/dev/null &

    sudo timeshift --create --comments "AUR packages upgrade"
    echo -e "\n"
    echo "Upgrading official packages..."
    sudo pacman -Syu


    exec $(dirname $(dirname $(realpath $0)))/ArchLinux-Maintenance
